name: tell_me_doctor
description: "Contact a doctor"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.10.1
  go_router: ^14.2.0
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  equatable: ^2.0.5
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  image_picker: ^1.1.2
  cloud_firestore: ^5.2.0
  heroicons: ^0.10.0
  language_detector: ^1.0.0
  firebase_storage: ^12.4.1
  flutter_svg: ^2.0.10+1
  iconsax: ^0.0.8
  flutter_secure_storage: ^9.2.4
  riverpod_lint: ^2.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
flutter:
  uses-material-design: true
  assets:
    - assets/doctor_background.png
    - assets/google-logo-carre-2015-09-400.png
    - assets/avatar_placeholder.png
    - assets/.env
    - assets/app_logo.png
    - assets/undraw_doctor_kw-5-l.svg
    - assets/healthcenter.png
    - assets/health/